### ISSUE TITLE
Code and Data

### ISSUE THREAD

**Issue by uniquefine** [DebanjanaKar/ArgFuse#1]
I read in [your paper](https://aclanthology.org/2021.case-1.5.pdf) that the code and data of this project are available in this repository. 
What is the current status here? When will the code and data be published?

**Comment by DebanjanaKar** [comment]
Hey @uniquefine , sorry for the delay, the code and data has been published in this repository as mentioned in the paper. Please raise an issue if you have any other concerns with the code/data.
